parameters:
    Hashids.class:      Hashids\Hashids

services:
    Hashids\HashidsInterface: '@hashids'

    hashids:
        class: "%Hashids.class%"
        arguments: ["%cayetanosoriano_hashids.salt%", "%cayetanosoriano_hashids.min_hash_length%", "%cayetanosoriano_hashids.alphabet%"]
